bert_classifier/urls.py
from django.urls import path
from . import views

# Ссылки на обновленные представления
app_name = 'bert_classifier'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:task_id>/', views.detail, name='detail'),
    path('<int:task_id>/predict/', views.predict, name='predict'),
]

dialog_bot/urls.py
from django.urls import path
from . import views

app_name = 'dialog_bot'
urlpatterns = [
    path('<int:task_id>/', views.detail, name='detail'),
    path('<int:task_id>/predict/', views.predict, name='predict'),
]

image_classification/urls.py
from django.urls import path
from . import views

app_name = 'image_classification'
urlpatterns = [
    path('<int:task_id>/', views.detail, name='detail'),
    path('<int:task_id>/predict/', views.predict, name='predict'),
]

nerualnet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bert_classifier/', include('bert_classifier.urls')),
    path('dialog_bot/', include('dialog_bot.urls')),
    path('image_classification/', include('image_classification.urls')),
]

bert_classifier/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    task_name = models.CharField(max_length=50)
    def __str__(self):
        return self.task_name
class InteractionML(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    input_data = models.CharField(max_length=200)
    output_data = models.CharField(max_length=200)
    def __str__(self):
        return f"input: {self.input_data}, output: {self.output_data}"

dialog_bot/models.py
from django.db import models

# nothing here :)

image_classification/models.py
from django.db import models
from bert_classifier.models import Task


class Image(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images')
    image_class = models.CharField(max_length=100)

image_classification/forms.py
from .models import Image
from django import forms


class UserImage(forms.ModelForm):
    class Meta:
        # To specify the model to be used to create form
        model = Image
        # It includes all the fields of model
        fields = ["image"]

bert_classifier/views.py
from django.http import HttpResponseRedirect
from .models import Task
from django.shortcuts import get_object_or_404, render
from .apps import BertClassifierConfig
from django.urls import reverse


# Необходимо импортировать модель Task из файла с описанием всех моделей. Для загрузки, наполнения
# и отображения шаблона HTML документа будем использовать метод render.
def index(request):
    tasks_list = Task.objects.all()
    context = {'tasks_list': tasks_list}
    return render(request, 'bert_classifier/index.html', context)

# По идентификатору задачи (task_id) получаем содержимое, либо ошибку Http404, если объекта не существует.
# Метод get_object_or_404 позволяет проделать это сокращённым кодом.
def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    latest_predictions = task.interactionml_set.order_by('-id')[:6][::-1]
    context = {
        'task': task,
        'latest_predictions': latest_predictions
    }
    return render(request, 'bert_classifier/detail.html', context)

# По task_id получаем содержимое запроса, отправляем в классификатор, отображаем его ответ, предварительно
# создав взаимодействие (InteractionML). После исполнения остаемся на той же странице, но с обновленной информацией.
def predict(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    input_text = request.POST['text']
    output = BertClassifierConfig.predictor.predict(input_text)

    task.interactionml_set.create(input_data=input_text, output_data=output)
    return HttpResponseRedirect(reverse('bert_classifier:detail', args=(task.id,)))

dialog_bot/views.py
from django.http import HttpResponseRedirect
from bert_classifier.models import Task
from django.shortcuts import get_object_or_404, render
from .apps import DialogBotConfig
from django.urls import reverse


def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    latest_predictions = task.interactionml_set.order_by('-id')[:3][::-1]
    context = {
        'task': task,
        'latest_predictions': latest_predictions
    }
    return render(request, 'dialog_bot/detail.html', context)


def predict(request, task_id):

    # Ищем задачу
    task = get_object_or_404(Task, pk=task_id)

    # Получение текста ввода из POST-запроса
    input_text = request.POST['text']

    # Генерация ответа от бота
    output = DialogBotConfig.dialog_bot.predict(input_text)

    # Создание новой записи с входными данными и сгенерированным выводом
    task.interactionml_set.create(input_data=input_text, output_data=output)

    return HttpResponseRedirect(reverse('dialog_bot:detail', args=(task.id,)))

image_classification/views.py
import os
from django.http import HttpResponseRedirect
from bert_classifier.models import Task
from django.shortcuts import get_object_or_404, render
from .apps import ImageClassificationConfig
from django.urls import reverse
from image_classification.forms import UserImage
from django.conf import settings


def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    latest_predictions = task.image_set.order_by('-id')[:1][::-1]
    context = {
        'task': task,
        'latest_predictions': latest_predictions
    }

    if request.method == 'POST':
        form = UserImage(request.POST, request.FILES, initial={'task': task_id})
        if form.is_valid():
            form.save()
            context["image"] = form.instance
    else:
        form = UserImage(initial={'task': task_id})

    context["form"] = form

    return render(request, 'image_classification/detail.html', context)


def predict(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    if request.method == 'POST':
        form = UserImage(request.POST, request.FILES, initial={'task': task_id})
        if form.is_valid():
            form.instance.task = task
            form.save()
            image_path = os.path.join(settings.BASE_DIR,
                                      *[x for x in form.instance.image.url.split('/')])
            output = ImageClassificationConfig.predictor.predict(image_path)
            form.instance.image_class = output
            form.save()

    return HttpResponseRedirect(reverse('image_classification:detail', args=(task.id,)))

bert_classifier/templates/bert_classifier/detail.html
{% extends 'base.html' %}

{% block title %}{{ task.task_name }}{% endblock %}

{% block content %}

<h2>{{task.task_name}}</h2>

<form action="{% url 'bert_classifier:index' %}" method="POST">

    {% csrf_token %}

    <button type="submit">На главную</button>

</form>

<hr>

    {% if latest_predictions %}

        {% for p in latest_predictions %}
            <p>
                <strong>{{p.input_data}}</strong>
                <pre>{{p.output_data}}</pre>
            </p>
        {% endfor %}

    {% else %}
    Нет предыдущих результатов.
    {% endif %}

</hr>

<form action="{% url 'bert_classifier:predict' task.id %}" method="POST">

    {% csrf_token %}

    <textarea name="text" required="" placeholder="Введите текст" cols="70" rows="10"></textarea><br>
    <button type="submit">Классифицировать текст</button>

</form>

{% endblock %}

bert_classifier/templates/bert_classifier/index.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'bert_classifier/style.css' %}">

{% if tasks_list %}
<ul>
    {% for task in tasks_list %}
        {% if task.task_name == "Text Classification" %}
            <li><a href="{% url 'bert_classifier:detail' task.id %}">{{ task.task_name }}</a></li>
        {% endif %}
        {% if task.task_name == "Image Classification" %}
            <li><a href="{% url 'image_classification:detail' task.id %}">{{ task.task_name }}</a></li>
        {% endif %}
        {% if task.task_name == "Dialog Bot" %}
            <li><a href="{% url 'dialog_bot:detail' task.id %}">{{ task.task_name }}</a></li>
        {% endif %}

    {% endfor %}
</ul>
{% else %}
<p>No tasks are available.</p>
{% endif %}

{% endblock %}

dialog_bot/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django ML backend{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

dialog_bot/templates/dialog_bot/detail.html
{% extends 'base.html' %}

{% block title %}{{ task.task_name }}{% endblock %}

{% block content %}

<h2>{{task.task_name}}</h2>

<form action="{% url 'bert_classifier:index' %}" method="POST">

    {% csrf_token %}

    <button type="submit">На главную</button>

</form>

<hr>

    {% if latest_predictions %}

        {% for p in latest_predictions %}
            <p>
                <strong>Вы: {{p.input_data}}</strong>
                <p>Бот: {{p.output_data}}</p>
            </p>
        {% endfor %}

    {% else %}
    Нет предыдущих результатов.
    {% endif %}

</hr>

<form action="{% url 'dialog_bot:predict' task.id %}" method="POST">

    {% csrf_token %}

    <textarea name="text" required="" placeholder="Введите текст" cols="70" rows="10"></textarea><br>
    <button type="submit">Отправить сообщение</button>

</form>

{% endblock %}

image_classification/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django ML backend{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

image_classification/templates/image_classification/detail.html
{% extends 'base.html' %}

{% block title %}{{ task.task_name }}{% endblock %}

{% block content %}

<h2>{{task.task_name}}</h2>

<form action="{% url 'bert_classifier:index' %}" method="POST">

    {% csrf_token %}

    <button type="submit">На главную</button>

</form>

<hr>

    {% if latest_predictions %}

        {% for p in latest_predictions %}
            <p>
                <strong>Image</strong><br>
                <img src="{{ p.image.url }}" alt="img" style="max-height:200px"><br>
                <strong>Prediction:</strong>
                <pre>{{ p.image_class }}</pre>
            </p>
        {% endfor %}

    {% else %}
    Нет предыдущих результатов.
    {% endif %}

</hr>

<form action="{% url 'image_classification:predict' task.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Загрузить</button>
</form>

{% endblock %}

image_classification/templates/image_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Загрузить</button>
    </form>

    {% if img_obj %}
        <h3>Изображение загружено</h3>
        <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
    {% endif %}

{% endblock content %}